"""gaps, feedback and daily usage

Revision ID: 3e361d29c23a
Revises: 7d1a62048f3a
Create Date: 2026-10-08 22:13:58.241472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '3e361d29c23a'
down_revision: Union[str, Sequence[str], None] = '7d1a62048f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_day'), 'feedback', ['day'], unique=False)
    op.create_table('gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('origin', sa.Enum('sem_evidencia', 'feedback_negativo', name='gap_origin'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gaps_day'), 'gaps', ['day'], unique=False)
    op.create_table('usage_daily',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('answered', sa.Integer(), nullable=False),
    sa.Column('refused', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_daily')
    op.drop_index(op.f('ix_gaps_day'), table_name='gaps')
    op.drop_table('gaps')
    op.drop_index(op.f('ix_feedback_day'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
